// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.2.1";

// src/lib/mcp/tools/list-cases.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-cases.ts
var CASE_STATUS = [
  "draft",
  "pending_payment",
  "design",
  "production",
  "delivery",
  "final_production",
  "completed",
  "remake"
];
var list_cases_default = defineTool({
  name: "list_cases",
  title: "List cases",
  description: "List dental cases visible to the signed-in user, optionally filtered by status, newest first.",
  inputSchema: {
    status: z.enum(CASE_STATUS).optional().describe("Filter by case status."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum cases to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cases").select("id, patient_initials, case_type, material, tooth_number, status, current_stage, progress, due_date, lab_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-case.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_case_default = defineTool2({
  name: "get_case",
  title: "Get case details",
  description: "Get one dental case with its recent status updates and production stages, by case ID.",
  inputSchema: {
    case_id: z2.string().uuid().describe("The case ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ case_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: kase, error } = await supabase.from("cases").select("*").eq("id", case_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!kase) {
      return { content: [{ type: "text", text: "Case not found or not accessible" }], isError: true };
    }
    const [{ data: updates }, { data: stages }] = await Promise.all([
      supabase.from("case_updates").select("id, status, message, created_at").eq("case_id", case_id).order("created_at", { ascending: false }).limit(20),
      supabase.from("case_stages").select("*").eq("case_id", case_id)
    ]);
    const payload = { case: kase, updates: updates ?? [], stages: stages ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-case.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z3 } from "npm:zod@^3.25.76";
var CASE_TYPE = ["crown", "veneer", "implant", "bridge", "denture", "aligner", "other"];
var create_case_default = defineTool3({
  name: "create_case",
  title: "Create case",
  description: "Create a new draft dental case for the signed-in dentist, with patient initials, case type and optional details.",
  inputSchema: {
    patient_initials: z3.string().trim().min(1).max(10).describe("Patient initials, e.g. 'A.M.'"),
    case_type: z3.enum(CASE_TYPE).describe("Type of restoration."),
    material: z3.string().trim().optional().describe("Material, e.g. Zirconia, E-max."),
    tooth_number: z3.string().trim().optional().describe("Tooth number or range."),
    due_date: z3.string().date().optional().describe("Requested due date (YYYY-MM-DD)."),
    lab_id: z3.string().uuid().optional().describe("Lab to assign the case to."),
    notes: z3.string().trim().max(2e3).optional().describe("Clinical notes for the lab.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cases").insert({
      dentist_id: ctx.getUserId(),
      patient_initials: input.patient_initials,
      case_type: input.case_type,
      material: input.material ?? null,
      tooth_number: input.tooth_number ?? null,
      due_date: input.due_date ?? null,
      lab_id: input.lab_id ?? null,
      notes: input.notes ?? null,
      status: "draft"
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { case: data }
    };
  }
});

// src/lib/mcp/tools/add-case-update.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z4 } from "npm:zod@^3.25.76";
var CASE_STATUS2 = [
  "draft",
  "pending_payment",
  "design",
  "production",
  "delivery",
  "final_production",
  "completed",
  "remake"
];
var add_case_update_default = defineTool4({
  name: "add_case_update",
  title: "Add case update",
  description: "Post a status update with an optional message to a case the signed-in user can access.",
  inputSchema: {
    case_id: z4.string().uuid().describe("The case ID."),
    status: z4.enum(CASE_STATUS2).describe("Status reported by this update."),
    message: z4.string().trim().max(1e3).optional().describe("Note to show on the case timeline.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ case_id, status, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("case_updates").insert({ case_id, status, message: message ?? null, created_by: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { update: data }
    };
  }
});

// src/lib/mcp/tools/search-labs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.2.1";
import { z as z5 } from "npm:zod@^3.25.76";
var search_labs_default = defineTool5({
  name: "search_labs",
  title: "Search labs",
  description: "Search the marketplace of dental labs by name or specialty, with rating, turnaround and base price.",
  inputSchema: {
    query: z5.string().trim().optional().describe("Text to match against the lab name."),
    specialty: z5.string().trim().optional().describe("Specialty the lab must offer, e.g. Zirconia."),
    verified_only: z5.boolean().default(false).describe("Only return verified labs."),
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum labs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, specialty, verified_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("labs").select("id, name, description, specialties, certifications, rating, total_reviews, avg_turnaround_days, base_price, is_verified").order("rating", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.ilike("name", `%${query}%`);
    if (specialty) q = q.contains("specialties", [specialty]);
    if (verified_only) q = q.eq("is_verified", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { labs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.2.1";
var get_my_profile_default = defineTool6({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's Dentaleem profile: name, clinic, specialty and verification status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "myupobattupvicqrpmgn";
var mcp_default = defineMcp({
  name: "dentaleem-labconnect",
  title: "dentaleem-labconnect",
  version: "0.1.0",
  instructions: "Tools for Dentaleem LabConnect, a dental clinic and lab case platform. Use `list_cases` and `get_case` to review cases, `create_case` to open a new draft case, `add_case_update` to post a status update, `search_labs` to browse the lab marketplace, and `get_my_profile` for the signed-in user's account details. All tools act as the signed-in user and only return data that user may access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_cases_default,
    get_case_default,
    create_case_default,
    add_case_update_default,
    search_labs_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.2.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
